import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { CATEGORIES, Category } from '@/types/prompt';
import { useState, useEffect } from 'react';
import { Send, Image, Link, Sparkles, Tag } from 'lucide-react';
import { ImageUpload } from './ImageUpload';
import { toast } from '@/hooks/use-toast';
import { generateSEODescription, generateTags } from '@/lib/seoHelpers';

interface SubmitPromptModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (data: SubmitPromptData) => void;
}

export interface SubmitPromptData {
  title: string;
  description: string;
  content: string;
  imageUrl: string;
  category: Category;
  tags?: string[];
}

type ImageInputMode = 'upload' | 'url';

export function SubmitPromptModal({ isOpen, onClose, onSubmit }: SubmitPromptModalProps) {
  const [formData, setFormData] = useState<SubmitPromptData>({
    title: '',
    description: '',
    content: '',
    imageUrl: '',
    category: 'profile',
    tags: [],
  });
  const [imageInputMode, setImageInputMode] = useState<ImageInputMode>('upload');
  const [autoGenerated, setAutoGenerated] = useState(false);
  
  // Auto-generate description and tags when category changes
  useEffect(() => {
    if (formData.category && !autoGenerated) {
      const seoDescription = generateSEODescription(formData.category, formData.title);
      const tags = generateTags(formData.category);
      setFormData(prev => ({
        ...prev,
        description: prev.description || seoDescription,
        tags: tags,
      }));
    }
  }, [formData.category, formData.title, autoGenerated]);

  const handleCategoryChange = (value: Category) => {
    setAutoGenerated(false);
    const seoDescription = generateSEODescription(value, formData.title);
    const tags = generateTags(value);
    setFormData(prev => ({
      ...prev,
      category: value,
      description: seoDescription,
      tags: tags,
    }));
    setAutoGenerated(true);
  };

  const handleAutoGenerate = () => {
    const seoDescription = generateSEODescription(formData.category, formData.title);
    const tags = generateTags(formData.category);
    setFormData(prev => ({
      ...prev,
      description: seoDescription,
      tags: tags,
    }));
    setAutoGenerated(true);
    toast({
      title: "✨ Gerado automaticamente",
      description: "Descrição SEO e tags foram preenchidas!",
    });
  };
  
  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSubmit(formData);
    setFormData({
      title: '',
      description: '',
      content: '',
      imageUrl: '',
      category: 'profile',
      tags: [],
    });
    setAutoGenerated(false);
    onClose();
  };

  const handleImageUploadError = (error: string) => {
    toast({
      title: "Erro no upload",
      description: error,
      variant: "destructive",
    });
  };

  const handleClose = () => {
    setFormData({
      title: '',
      description: '',
      content: '',
      imageUrl: '',
      category: 'profile',
      tags: [],
    });
    setAutoGenerated(false);
    onClose();
  };
  
  return (
    <Dialog open={isOpen} onOpenChange={handleClose}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="font-display text-2xl flex items-center gap-2">
            <span className="text-2xl">🍌</span>
            Enviar Novo Prompt
          </DialogTitle>
        </DialogHeader>
        
        <form onSubmit={handleSubmit} className="space-y-6">
          <div className="space-y-2">
            <Label htmlFor="title">Título do Prompt</Label>
            <Input
              id="title"
              value={formData.title}
              onChange={(e) => setFormData({ ...formData, title: e.target.value })}
              placeholder="Ex: Cartão de citação com retrato estilizado"
              required
              className="border-2 border-primary"
            />
          </div>
          
          <div className="space-y-2">
            <Label htmlFor="category">Categoria</Label>
            <Select 
              value={formData.category} 
              onValueChange={(value) => handleCategoryChange(value as Category)}
            >
              <SelectTrigger className="border-2 border-primary">
                <SelectValue placeholder="Selecione uma categoria" />
              </SelectTrigger>
              <SelectContent>
                {CATEGORIES.filter(c => c.id !== 'all').map((cat) => (
                  <SelectItem key={cat.id} value={cat.id}>
                    {cat.labelPt}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label htmlFor="description">Descrição SEO</Label>
              <Button
                type="button"
                variant="ghost"
                size="sm"
                onClick={handleAutoGenerate}
                className="gap-1 text-xs text-primary hover:text-primary/80"
              >
                <Sparkles className="w-3 h-3" />
                Gerar automaticamente
              </Button>
            </div>
            <Input
              id="description"
              value={formData.description}
              onChange={(e) => {
                setFormData({ ...formData, description: e.target.value });
                setAutoGenerated(false);
              }}
              placeholder="Uma breve descrição otimizada para SEO"
              required
              className="border-2 border-primary"
            />
            {autoGenerated && (
              <p className="text-xs text-muted-foreground flex items-center gap-1">
                <Sparkles className="w-3 h-3 text-primary" />
                Descrição gerada automaticamente com base na categoria
              </p>
            )}
          </div>

          {/* Tags */}
          {formData.tags && formData.tags.length > 0 && (
            <div className="space-y-2">
              <Label className="flex items-center gap-2">
                <Tag className="w-4 h-4" />
                Tags (geradas automaticamente)
              </Label>
              <div className="flex flex-wrap gap-2">
                {formData.tags.map((tag, index) => (
                  <span
                    key={index}
                    className="px-2 py-1 bg-primary/10 text-primary text-xs rounded-full font-medium"
                  >
                    #{tag}
                  </span>
                ))}
              </div>
            </div>
          )}
          
          <div className="space-y-2">
            <Label htmlFor="content">Prompt Completo</Label>
            <Textarea
              id="content"
              value={formData.content}
              onChange={(e) => setFormData({ ...formData, content: e.target.value })}
              placeholder="Cole aqui o prompt completo que será usado para gerar imagens..."
              required
              className="min-h-[150px] border-2 border-primary font-mono text-sm"
            />
          </div>
          
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <Label className="flex items-center gap-2">
                <Image className="w-4 h-4" />
                Imagem de Exemplo (opcional)
              </Label>
              <div className="flex gap-1 bg-muted rounded-lg p-1">
                <button
                  type="button"
                  onClick={() => setImageInputMode('upload')}
                  className={`px-3 py-1 text-xs font-medium rounded transition-colors ${
                    imageInputMode === 'upload' 
                      ? 'bg-card text-foreground shadow-sm' 
                      : 'text-muted-foreground hover:text-foreground'
                  }`}
                >
                  Upload
                </button>
                <button
                  type="button"
                  onClick={() => setImageInputMode('url')}
                  className={`px-3 py-1 text-xs font-medium rounded transition-colors flex items-center gap-1 ${
                    imageInputMode === 'url' 
                      ? 'bg-card text-foreground shadow-sm' 
                      : 'text-muted-foreground hover:text-foreground'
                  }`}
                >
                  <Link className="w-3 h-3" />
                  URL
                </button>
              </div>
            </div>

            {imageInputMode === 'upload' ? (
              <ImageUpload
                value={formData.imageUrl}
                onChange={(url) => setFormData({ ...formData, imageUrl: url })}
                onError={handleImageUploadError}
              />
            ) : (
              <div className="space-y-3">
                <Input
                  id="imageUrl"
                  type="url"
                  value={formData.imageUrl}
                  onChange={(e) => setFormData({ ...formData, imageUrl: e.target.value })}
                  placeholder="https://exemplo.com/imagem.jpg"
                  className="border-2 border-primary"
                />
                {formData.imageUrl && (
                  <div className="relative rounded-lg overflow-hidden border-2 border-primary">
                    <img
                      src={formData.imageUrl}
                      alt="Preview"
                      className="w-full h-48 object-cover pointer-events-none select-none"
                      draggable={false}
                      onContextMenu={(e) => e.preventDefault()}
                      onError={(e) => {
                        e.currentTarget.style.display = 'none';
                        handleImageUploadError("Não foi possível carregar a imagem. Verifique a URL.");
                      }}
                      onLoad={(e) => {
                        e.currentTarget.style.display = 'block';
                      }}
                    />
                  </div>
                )}
              </div>
            )}
          </div>
          
          <div className="flex gap-3 pt-4">
            <Button type="button" variant="outline" onClick={handleClose} className="flex-1">
              Cancelar
            </Button>
            <Button type="submit" variant="generate" className="flex-1 gap-2">
              <Send className="w-4 h-4" />
              Enviar para Revisão
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
}
